[project]
name = "pdfmerge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pypdf>=6.5.0",
    "pypdf2>=3.0.1",
    "streamlit>=1.52.2",
]
